[2022-05-25 09:17:06.558] [remoteagent] [info] Extension host agent started.
[2022-05-25 09:17:06.841] [remoteagent] [info] [127.0.0.1][99087d1e][ManagementConnection] New connection established.
[2022-05-25 09:17:06.893] [remoteagent] [info] [127.0.0.1][24629901][ExtensionHostConnection] New connection established.
[2022-05-25 09:17:06.898] [remoteagent] [info] [127.0.0.1][24629901][ExtensionHostConnection] <25420> Launched Extension Host Process.
[2022-05-25 09:17:09.150] [remoteagent] [error] ["Error: Could not find pty on pty host","    at m._throwIfNoPty (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:20:5333)","    at m.updateTitle (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:20:1673)","    at Object.call (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:13:8361)","    at g.onPromise (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:12:4879)","    at g.onRawMessage (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:12:4267)","    at /home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:12:3555","    at D.invoke (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at N.deliver (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:8:2271)","    at h.fire (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:8:1849)","    at process.p (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:6:34973)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-05-25 09:17:10.638] [remoteagent] [info] Getting Manifest... ms-python.vscode-pylance
[2022-05-25 09:17:10.708] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2022-05-25 09:17:11.417] [remoteagent] [info] Downloaded extension: ms-python.vscode-pylance /home/ubuntu/.vscode-server/data/CachedExtensionVSIXs/ms-python.vscode-pylance-2022.5.2
[2022-05-25 09:17:16.112] [remoteagent] [info] Extracted extension to /home/ubuntu/.vscode-server/extensions/.183efb56-13b8-41d0-a61a-817ba4fd933c: ms-python.vscode-pylance
[2022-05-25 09:17:16.132] [remoteagent] [info] Renamed to /home/ubuntu/.vscode-server/extensions/ms-python.vscode-pylance-2022.5.2
[2022-05-25 09:17:16.135] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2022-05-25 09:17:16.142] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2022-05-25 09:17:29.460] [remoteagent] [info] [127.0.0.1][99087d1e][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-05-25 09:17:29.484] [remoteagent] [info] [127.0.0.1][24629901][ExtensionHostConnection] <25420> Extension Host Process exited with code: 0, signal: null.
[2022-05-25 09:17:29.484] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-05-25 09:17:33.169] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-05-25 09:17:33.169] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-05-25 09:17:33.341] [remoteagent] [info] [127.0.0.1][658853d1][ManagementConnection] New connection established.
[2022-05-25 09:17:33.402] [remoteagent] [info] [127.0.0.1][1cbc5fd5][ExtensionHostConnection] New connection established.
[2022-05-25 09:17:33.409] [remoteagent] [info] [127.0.0.1][1cbc5fd5][ExtensionHostConnection] <25584> Launched Extension Host Process.
[2022-05-25 09:17:35.859] [remoteagent] [error] ["Error: Could not find pty on pty host","    at m._throwIfNoPty (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:20:5333)","    at m.updateTitle (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:20:1673)","    at Object.call (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:13:8361)","    at g.onPromise (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:12:4879)","    at g.onRawMessage (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:12:4267)","    at /home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:12:3555","    at D.invoke (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at N.deliver (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:8:2271)","    at h.fire (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:8:1849)","    at process.p (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/platform/terminal/node/ptyHostMain.js:6:34973)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-05-25 09:22:33.170] [remoteagent] [info] New EH opened, aborting shutdown
[2022-05-25 12:13:50.540] [remoteagent] [info] [127.0.0.1][658853d1][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-05-25 12:13:50.542] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/ubuntu/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/server/node/server.main.js:143:7914)
    at process.emit (node:events:390:28)
[2022-05-25 15:13:13.422] [remoteagent] [info] [127.0.0.1][1cbc5fd5][ExtensionHostConnection] <25584> Extension Host Process exited with code: 0, signal: null.
[2022-05-25 15:13:13.422] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-05-25 15:14:01.239] [remoteagent] [info] [127.0.0.1][658853d1][ManagementConnection] The reconnection grace time of 3h has expired, so the connection will be disposed.
[2022-05-25 15:18:13.423] [remoteagent] [info] Last EH closed, shutting down
